
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://justingrierson.github.io"

name: "Justin's Blog"

smallimage: "/img/tinyauthor1.jpg"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "https://ju3tin.github.io"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Justin Grierson"
title: "{ Justin Grierson }"
description: "Blog and website of Justin Grierson, blogging mainly for tech. Opinions expressed are mine."
keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "justingrierson"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "ju3tin@hotmail.co.uk"

################
# Author Blurb #
################
type: "article"
# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Justin Grierson is an awesome person. He lives in England, where he works on projects. In his spare time, Justin likes to eat pizza."
author_blurb_image: "/img/author.png"
author_tinyimage: "/img/tinyauthor.jpg"
siteimage: "/assets/img/bg-office1.jpg"
##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/justin.grierson.5"
  - title: "twitter"
    url: "https://twitter.com/ju3t1ng"
  - title: "github"
    url: "https://github.com/ju3tin"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: justing
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS
jekyll-archives:
  enabled:
    - categories
    - tags
sass:
  style: compressed

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jemoji
  
compress_html:
  clippings: all
  ignore:
    envs: development
    


# Site Settings
title: Justin Grierson
description: Blog and website of Justin Grierson, blogging mainly for tech. Opinions expressed are mine.
url:

# Jekyll Configuration
encoding: UTF-8
# permalink: /:title/
permalink: /:title.html
paginate: 5
paginate_path: "/blog/page/:num/"
media_folder: "/img/galleries/gallery-standard-post"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Custom Collections
collections:
  products:
    output: true

# Collection Defaults
defaults:   
- scope:
    type: posts
  values:
    layout: post
- scope:
    type: pages
  values:
    layout: page
- scope:
    type: products
  values:
    layout: product

# Frontmatter Defaults
sidebar_options:
  - sidebar
  - no-sidebar

# File Handling
# include: [_pages]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json]

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

gems: [jekyll-paginate]
